# Site settings
title: "Aaron Earles"
description: "Jekyll Resume for Github Pages"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Aaron Earles"
resume_title:                   "Senior Cloud Infrastructure Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "aaron@earles.io"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "(435) 922-1624"
resume_contact_address:         "St. George, Utah"

resume_header_contact_info:     "St. George, Utah • (435) 922-1624 • aaron@earles.io"
display_header_contact_info:    "true"

resume_header_intro: "<p>Results-driven Cloud Engineer combining deep Azure expertise with enterprise networking and security experience. Proven track record in infrastructure automation, systems optimization, and implementing scalable cloud solutions.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
# resume_section_projects:        true
resume_section_skills:          true
# resume_section_recognition:     true
# resume_section_links:           true
# resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_linkedin_url:          "https://www.linkedin.com/in/aearles"
  resume_github_url:            "https://github.com/aaronearles"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://joelglovier.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
